snowflake_credentials:
  user: ""
  password: ""
  host: "" # to be host url
  account: ""
  role: SYSADMIN
  default_warehouse: ""
  default_database: ""
  default_schema: ""

postgres_credentials:
  user: ""
  password: ""
  host: "" # to be host url
  port: ""
  default_database: ""

aws_credentials:
  s3_url: https://s3.console.aws.amazon.com/s3/buckets/
  access_key_id: ""
  secret_access_key: ""
  region: ""
